# Generated by Django 4.2.5 on 2025-05-21 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_pacienterecepcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacienterecepcion',
            name='nombre_apellido',
        ),
        migrations.AddField(
            model_name='pacienterecepcion',
            name='apellido',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pacienterecepcion',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
    ]
