# Generated by Django 4.2.5 on 2025-05-22 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion', '0003_remove_pacienterecepcion_nombre_apellido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ausente', 'Ausente'), ('con_paciente', 'Con paciente'), ('desconectado', 'Desconectado')], default='desconectado', max_length=20)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estado_doctor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
