# Generated by Django 5.2.4 on 2025-07-07 22:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_registro_caja_destino'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='pacienterecepcion',
            options={'ordering': ['-fecha_ingreso']},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='registro',
            options={'ordering': ['-fecha', '-id']},
        ),
        migrations.AlterModelOptions(
            name='tratamiento',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterField(
            model_name='pacienterecepcion',
            name='dni',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pacienterecepcion',
            name='fecha_ingreso',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='estado',
            field=models.CharField(choices=[('para_abonar', 'Para Abonar'), ('abonado', 'Abonado')], db_index=True, default='para_abonar', max_length=20),
        ),
        migrations.AlterField(
            model_name='registro',
            name='fecha',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='nombre',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='pacienterecepcion',
            index=models.Index(fields=['-fecha_ingreso', 'estado'], name='idx_paciente_ingreso_estado'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.sector'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='caja_destino',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion.sector', verbose_name='Caja Destino'),
        ),
        migrations.AddIndex(
            model_name='registro',
            index=models.Index(fields=['caja_destino', 'fecha', 'estado'], name='idx_registro_caja_optimized'),
        ),
        migrations.AddIndex(
            model_name='registro',
            index=models.Index(fields=['doctor', 'fecha'], name='idx_registro_doctor_optimized'),
        ),
        migrations.AddIndex(
            model_name='registro',
            index=models.Index(fields=['-fecha', 'estado'], name='idx_registro_recent'),
        ),
    ]
