# Generated by Django 4.2.6 on 2024-07-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_perfilusuario_sector_alter_pacienterecepcion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='apellido',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]